### ISSUE TITLE
Interpreter or Compiler?

### ISSUE THREAD

**Issue by TheQMechanic** [dev-orus/wyst#3]
Hello there! Is Wisp compiled or interpreted? By the looks of it, it seems to be interpreted, however, I do not have experience in Rust so I could be wrong. Thank you! 

Happy coding!

**Comment by selimaj-dev** [comment]
Hello. Thanks for asking! The language is compiled to rust which means you get all the atvantages of rust but in result of cleaner code

**Comment by Xtqm** [comment]
Oh got it! Sounds very interesting. Is there somewhere I can read the documentation for Wisp?

**Comment by blinkelys** [comment]
> Oh got it! Sounds very interesting. Is there somewhere I can read the documentation for Wisp?

Since it is still in the early phase, we have not gotten to write a proper documentation but it will be on the website when that releases

**Comment by selimaj-dev** [comment]
We are currently writing the grammar. it still has a mix of rust on the syntax though
this is a example:
```c
use std::collections::HashMap;
#Include "my_module.ws"
#include <globa_module.ws> // it can also be .rs

void main() {
    i32 mut x; // might also implement a int
    while x < 10 {
        x++
    }
   printf("{x}"); // This is a macro
}
```

printf is a macro. To run macros like that instead of printf! you need to add the name of the macro you want to add to the macros array in Wisp.toml

This is the plan

**Comment by Xtqm** [comment]
> > Oh got it! Sounds very interesting. Is there somewhere I can read the documentation for Wisp?
> 
> Since it is still in the early phase, we have not gotten to write a proper documentation but it will be on the website when that releases

What's the link to the website? 
And if you guys need help maybe I could help with the documentation. 


> We are currently writing the grammar. it still has a mix of rust on the syntax though this is a example:
> 
> ```c
> use std::collections::HashMap;
> #Include "my_module.ws"
> #include <globa_module.ws> // it can also be .rs
> 
> void main() {
>     i32 mut x; // might also implement a int
>     while x < 10 {
>         x++
>     }
>    printf("{x}"); // This is a macro
> }
> ```
> 
> printf is a macro. To run macros like that instead of printf! you need to add the name of the macro you want to add to the macros array in Wisp.toml
> 
> This is the plan

Ok, thanks for letting me know! 

Happy coding!
