### ISSUE TITLE
Line system not working

### ISSUE THREAD

**Issue by selimaj-dev** [dev-orus/wyst#5]
I'm not exactly sure how to fix this, Mutable state in the transpiler and not lexer? or passing it to other function calls that transpile the inner tokens that need the line tracking.

let's say i pass this as the input:
```c
void main() {
    int x;
}
```

```javascript
VoidFunctionDeceleration: [
    (TokenType: Identifier, TokenValue: "void", Line: 1, Column: 1),
    (TokenType: Identifier, TokenValue: "main", Line: 1, Column: 6),
    (TokenType: Round, TokenValue: """, Line: 1, Column: 10),
    (TokenType: Curly, TokenValue: "    int x;", Line: 3, Column: 11)
]
VariableDeceleration: [
    (TokenType: Identifier, TokenValue: "int", Line: 1, Column: 5),
    (TokenType: Identifier, TokenValue: "x", Line: 1, Column: 9)
]
Other: [
    (TokenType: Semicolon, TokenValue: ";", Line: 1, Column: 10)
]
```

you can see theat the variable decleration is at line 1 which is fine and can be tuned in the transpiler code and a little lexer code but where it gets a little tricky is the
```js
(TokenType: Curly, TokenValue: "    int x;", Line: 3, Column: 11)
```

The line where the curly bracket is at the first line.

I Think the problem with this is that we need to define the state where it first detected the bracket or qoute.

**Comment by RudideC** [comment]
k imma try to fix this
